# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e673c16b8e79586b6a018e7df2b7797675ac15590f3bbcb3bf59ee2b5ee616072e5b0868ecd7212aaa5313d31c334bf9193804c1ab05fe1bd2e062d42e545939

test:
  secret_key_base: 00d833d484c2935274aecb7666e36c3a00593861bbc2e0bb630591982fbbed5f815b9fb1370f3e3c4e156e1563661db46eb3a8ff9579e5684b8b63e364893cc4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
